### ISSUE TITLE
如何修改端口呢？

### ISSUE THREAD

**Issue by williamnie** [LeeJiangWei/go-message#3]
80端口一般会被nginx占用，如何配置到其他端口呢？

**Comment by williamnie** [comment]
[root@VM-16-12-centos ~]# ./go-message-linux-amd64 
2022/04/02 16:37:42 Can not find config file. Generating default config.
2022/04/02 16:37:42 Config loaded.

2022/04/02 16:37:42 D:/projects/go-message/model/util.go:12
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
panic: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

goroutine 1 [running]:
main.main()
        D:/projects/go-message/main.go:35 +0x51c


centos运行会报如上的错误，是为什么呢

**Comment by williamnie** [comment]
[root@VM-16-12-centos go-message-main]# ./go-message 
2022/04/02 16:45:18 Can not find config file. Generating default config.
2022/04/02 16:45:18 Config loaded.
2022/04/02 16:45:18 Database initialized.
2022/04/02 16:45:18 Cache initialized.
2022/04/02 16:45:18 Router set.
2022/04/02 16:45:18 Scheduler set.
2022/04/02 16:45:18 Server started.
panic: listen tcp :80: bind: address already in use

goroutine 1 [running]:
main.main()
        /root/go-message-main/main.go:71 +0x72f

自己编译完了以后，启动会提示80端口被占用，建议更换或者可以指定端口运行

**Comment by LeeJiangWei** [comment]
初次运行后应该会生成一个配置文件 `config.yaml`，里面可以修改
稍后我更新下 release，可能是自己打包的时候忘记设参数了

**Comment by williamnie** [comment]
> 初次运行后应该会生成一个配置文件 `config.yaml`，里面可以修改 稍后我更新下 release，可能是自己打包的时候忘记设参数了

直接改了源码，重新build的，哈哈，还有个问题，就是程序一直能注册，会不会有安全问题呢，被恶意注册？

**Comment by LeeJiangWei** [comment]
确实有可能，后面再想想怎么改吧
